name: Prism Multi-Account Mailer

on:
  schedule:
    - cron: "0 * * * *"   # Har ghante start hoga (UTC time)
  workflow_dispatch:       # Manual run bhi possible

jobs:
  send-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run mailer script
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

          SMTP_USER_JOHNDISPATCHER: ${{ secrets.SMTP_USER_JOHNDISPATCHER }}
          SMTP_PASS_JOHNDISPATCHER: ${{ secrets.SMTP_PASS_JOHNDISPATCHER }}

          SMTP_USER_ANDREWDISPATCHER: ${{ secrets.SMTP_USER_ANDREWDISPATCHER }}
          SMTP_PASS_ANDREWDISPATCHER: ${{ secrets.SMTP_PASS_ANDREWDISPATCHER }}

          SMTP_USER_ERICDISPATCHER: ${{ secrets.SMTP_USER_ERICDISPATCHER }}
          SMTP_PASS_ERICDISPATCHER: ${{ secrets.SMTP_PASS_ERICDISPATCHER }}

          SMTP_USER_TOMDISPATCHER: ${{ secrets.SMTP_USER_TOMDISPATCHER }}
          SMTP_PASS_TOMDISPATCHER: ${{ secrets.SMTP_PASS_TOMDISPATCHER }}

          SMTP_USER_AUSTINDISPATCHER: ${{ secrets.SMTP_USER_AUSTINDISPATCHER }}
          SMTP_PASS_AUSTINDISPATCHER: ${{ secrets.SMTP_PASS_AUSTINDISPATCHER }}

          SMTP_USER_OLIVERDISPATCHER: ${{ secrets.SMTP_USER_OLIVERDISPATCHER }}
          SMTP_PASS_OLIVERDISPATCHER: ${{ secrets.SMTP_PASS_OLIVERDISPATCHER }}

          SMTP_USER_DAVIDDISPATCHER: ${{ secrets.SMTP_USER_DAVIDDISPATCHER }}
          SMTP_PASS_DAVIDDISPATCHER: ${{ secrets.SMTP_PASS_DAVIDDISPATCHER }}

          SMTP_USER_WILLIAMDISPATCHER: ${{ secrets.SMTP_USER_WILLIAMDISPATCHER }}
          SMTP_PASS_WILLIAMDISPATCHER: ${{ secrets.SMTP_PASS_WILLIAMDISPATCHER }}

          SMTP_USER_HARRISONDISPATCHER: ${{ secrets.SMTP_USER_HARRISONDISPATCHER }}
          SMTP_PASS_HARRISONDISPATCHER: ${{ secrets.SMTP_PASS_HARRISONDISPATCHER }}

          SMTP_USER_PHILIPDISPATCHER: ${{ secrets.SMTP_USER_PHILIPDISPATCHER }}
          SMTP_PASS_PHILIPDISPATCHER: ${{ secrets.SMTP_PASS_PHILIPDISPATCHER }}

          SMTP_USER_MARTINDISPATCHER: ${{ secrets.SMTP_USER_MARTINDISPATCHER }}
          SMTP_PASS_MARTINDISPATCHER: ${{ secrets.SMTP_PASS_MARTINDISPATCHER }}

          SMTP_USER_WESLYDISPATCHER: ${{ secrets.SMTP_USER_WESLYDISPATCHER }}
          SMTP_PASS_WESLYDISPATCHER: ${{ secrets.SMTP_PASS_WESLYDISPATCHER }}

          SMTP_USER_JACKDISPATCHER: ${{ secrets.SMTP_USER_JACKDISPATCHER }}
          SMTP_PASS_JACKDISPATCHER: ${{ secrets.SMTP_PASS_JACKDISPATCHER }}

        run: node sendEmails.js
